#  넘파이(numpy)

In [3]:
# with open('./drive/MyDrive/ReadME.md','w') as f:
#     data = f.write('반가워요')
#     print('저장되었습니다')

#넘파이(numpy)


- ndim: 축의 개수
- shape: 배열의 차원정보
- size: 배열안에 있는 원소의 총 개수
- dtype:배열 원소의 자료형

## 1차원과 속성들

In [38]:
# pip install numpy
import numpy as np
narry = np.array(range(5))
print(narry,type(narry))
print(narry.ndim)
print(narry.shape)
print(narry.size)
print(narry.dtype)
print(narry[2:4])

[0 1 2 3 4] <class 'numpy.ndarray'>
1
(5,)
5
int64
[2 3]


In [39]:
narr1=np.array([1,2,3,4])
narr2=np.array([1,2,'a','b'])
narr3=np.array([1,2,3,4],dtype='str')
print(narr1,narr1.dtype)
print(narr2,narr2.dtype)
print(narr3,narr3.dtype)

[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' '3' '4'] <U1


In [46]:
narr4 = np.zeros((2,2),dtype='int64')
narr5 = np.ones((2,2))
narr6 = np.full((3,3),3)
narr7 = np.full((3,3),'number')
narr8 = np.eye(3)
narr9 = np.linspace(0,100,5,endpoint=False,dtype = 'int64')
narr10 = np.arange(0,100,20)
print(narr4, narr4.ndim, narr4.dtype, narr4.shape, narr4.size, type(narr4))
print(narr5, narr5.ndim, narr5.dtype, narr5.shape, narr5.size, type(narr5))
print(narr6, narr6.ndim, narr6.dtype, narr6.shape, narr6.size, type(narr6))
print(narr7, narr7.ndim, narr7.dtype, narr7.shape, narr7.size, type(narr7))
print(narr8, narr8.ndim, narr8.dtype, narr8.shape, narr8.size, type(narr8))
print(narr9, narr9.ndim, narr9.dtype, narr9.shape, narr9.size, type(narr9))
print(narr10, narr10.ndim, narr10.dtype, narr10.shape, narr10.size, type(narr10))

[[0 0]
 [0 0]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]] 2 float64 (2, 2) 4 <class 'numpy.ndarray'>
[[3 3 3]
 [3 3 3]
 [3 3 3]] 2 int64 (3, 3) 9 <class 'numpy.ndarray'>
[['number' 'number' 'number']
 ['number' 'number' 'number']
 ['number' 'number' 'number']] 2 <U6 (3, 3) 9 <class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 2 float64 (3, 3) 9 <class 'numpy.ndarray'>
[ 0 20 40 60 80] 1 int64 (5,) 5 <class 'numpy.ndarray'>
[ 0 20 40 60 80] 1 int64 (5,) 5 <class 'numpy.ndarray'>


## 2차원 배열

In [41]:
print(list(range(2,10)))
print(np.arange(2,10))
np.arange(10)

[2, 3, 4, 5, 6, 7, 8, 9]
[2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr1= np.array([[0,0],[0,0]])
print(arr1,arr1.ndim, arr1.dtype, arr1.shape, arr1.size)

[[0 0]
 [0 0]] 2 int64 (2, 2) 4


In [43]:
arr2 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr3 = np.arange(1,10).reshape(3,3)
arr4 = np.arange(1,11).reshape(2,5)
arr5 = np.arange(1,11).reshape(5,2)
arr6 = np.arange(1,28).reshape(3,3,3)
print('차원:',arr2.ndim, '/ 데이터타입:',arr2.dtype, '/ 형태:',arr2.shape, '/ 크기:',arr2.size,'\n', arr2)
print('차원:',arr3.ndim, '/ 데이터타입:',arr3.dtype, '/ 형태:',arr3.shape, '/ 크기:',arr3.size,'\n', arr3)
print('차원:',arr4.ndim, '/ 데이터타입:',arr4.dtype, '/ 형태:',arr4.shape, '/ 크기:',arr4.size,'\n', arr4)
print('차원:',arr5.ndim, '/ 데이터타입:',arr5.dtype, '/ 형태:',arr5.shape, '/ 크기:',arr5.size,'\n', arr5)
print('차원:',arr6.ndim, '/ 데이터타입:',arr6.dtype, '/ 형태:',arr6.shape, '/ 크기:',arr6.size,'\n', arr6)

차원: 2 / 데이터타입: int64 / 형태: (3, 3) / 크기: 9 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
차원: 2 / 데이터타입: int64 / 형태: (3, 3) / 크기: 9 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
차원: 2 / 데이터타입: int64 / 형태: (2, 5) / 크기: 10 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
차원: 2 / 데이터타입: int64 / 형태: (5, 2) / 크기: 10 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
차원: 3 / 데이터타입: int64 / 형태: (3, 3, 3) / 크기: 27 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [44]:
t1 = np.arange(1,22).reshape(3,7)
t2 = np.arange(1,8).reshape(7,1)
t3 = np.arange(1,11).reshape(5,2)
t4 = np.arange(1,22).reshape(3,7)
t5 = np.arange(1,13).reshape(4,3,1)
print(t1)
print('='*23)
print(t2)
print('='*23)
print(t3)
print('='*23)
print(t4)
print('='*23)
print(t5)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [45]:
# test
print(t1[1][2:5],'\n')
for i in range(3):
    print(t4[i][3:])
    print(type(t4[i][3:]))  
print('\n')
print(t4[0:3, 3:],'\n')
print(t4[1:3, 4:6],'\n')
print(t4[t4>12],'\n')
print(t4%2 == 0,'\n')

[10 11 12] 

[4 5 6 7]
<class 'numpy.ndarray'>
[11 12 13 14]
<class 'numpy.ndarray'>
[18 19 20 21]
<class 'numpy.ndarray'>


[[ 4  5  6  7]
 [11 12 13 14]
 [18 19 20 21]] 

[[12 13]
 [19 20]] 

[13 14 15 16 17 18 19 20 21] 

[[False  True False  True False  True False]
 [ True False  True False  True False  True]
 [False  True False  True False  True False]] 



In [103]:
# np 배열 연산 //shape 가 같을 경우 원소별 연산이 가능
np1 = np.array([6,7,8,9,10])
np2 = np.array([1,2,3,4,5])
print('덧셈:',np1+np2)
print('뺄셈:',np1-np2)
print('곱셈:',np1*np2)
print('나눗셈:',np1/np2)
print('제곱:',np1**2)

덧셈: [ 7  9 11 13 15]
뺄셈: [5 5 5 5 5]
곱셈: [ 6 14 24 36 50]
나눗셈: [6.         3.5        2.66666667 2.25       2.        ]
제곱: [ 36  49  64  81 100]


In [104]:
np1

array([ 6,  7,  8,  9, 10])

In [105]:
# 브로드캐스팅
np3 = np1 +10
print(np3)

[16 17 18 19 20]


In [113]:
br1 = np.arange(1,10).reshape(3,3)
br2 = np.array([11,22,33])
#스칼라와 연산
print(br1) 
print(br2)
print('========스칼라와 연산==========')
print(br1+3)
print(br1*2)
#2D와 1D의 연산
print('=========2D와 1D의 연산=========')
print(br1+br2)
print(br1*br2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[11 22 33]
========스칼라와 연산==========
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
=========2D와 1D의 연산=========
[[12 24 36]
 [15 27 39]
 [18 30 42]]
[[ 11  44  99]
 [ 44 110 198]
 [ 77 176 297]]


In [122]:
# flatten 처리
ff = np.arange(1,10).reshape(3,3)
print(br2.flatten())
print(ff.reshape(9))
print(ff.flatten())

[11 22 33]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


## Random number 발생

- np.random.randint(): 균일 분포의 정수 난수 
- np.random.rand(): 0부터 1사이의 균일분포 난수 생성
- np.random.randn(): 표준정규분포 난수 생성
- np.random.normal(): 정규분포 난수 생성

In [22]:
#randomint
import numpy as np
x = np.random.randint(1,300,size=(3,3,3))
x

array([[[109, 158,  40],
        [283, 270,   8],
        [129,  54, 170]],

       [[ 60, 272, 269],
        [195, 266, 115],
        [144, 215,  93]],

       [[213, 186, 197],
        [143, 246,  47],
        [223,  98, 133]]], dtype=int32)

In [23]:
print('평균값:',np.mean(x),'표준편차:',np.std(x),'최소값:',x.min(),'최대값:',x.max())

평균값: 160.59259259259258 표준편차: 79.38572465162518 최소값: 8 최대값: 283


In [24]:
print(len(x.flatten()))

27


In [35]:
y = np.array([0,1,2,3,4,6,34,2,0,23,3,1,2,3,0,0,12,3,5])
print(len(y))
print(np.count_nonzero(y)) #0을 제외한 숫자 개수

19
15


# 판다스(pandas)

- 시리즈(series)
- 데이터프레임(dataframe)

In [2]:
#!pip install pandas

In [3]:
import numpy as np
import pandas as pd

In [18]:
#판다스 기초
data1 = np.arange(1,6)
print(data1)
data2 = pd.Series(data1)
print(data2, type(data2),data2.index,data2.values, data2.dtype)

[1 2 3 4 5]
0    1
1    2
2    3
3    4
4    5
dtype: int64 <class 'pandas.core.series.Series'> RangeIndex(start=0, stop=5, step=1) [1 2 3 4 5] int64


In [19]:
#판다스 시리즈의 데이터 타입 -자동
data3 = pd.Series([1,2,3.14,4,5,6,7],) # dtype = "float")
print(data3)

0    1.00
1    2.00
2    3.14
3    4.00
4    5.00
5    6.00
6    7.00
dtype: float64


In [20]:
# 판다스 시리즈의 인덱스 설정
data3 = pd.Series([1,2,3,4],index=['a','b','c','d']) 
print(data3)

a    1
b    2
c    3
d    4
dtype: int64


In [33]:
# 판다스 시리즈 딕셔너리데이터
population_dict ={
    'korea':5182,
    'japan':12622,
    'china':141178,
    'usa':32976
}
# print(population_dict.keys())
# print(population_dict.values())
# print(population_dict.items())
country = pd.Series(population_dict)
print(country, country.index, country.values)
print(country.ndim, country.shape, country.size)
# 시리즈 원소에 접근방법
print(country.loc['korea'])
print(country.iloc[0])

korea      5182
japan     12622
china    141178
usa       32976
dtype: int64 Index(['korea', 'japan', 'china', 'usa'], dtype='object') [  5182  12622 141178  32976]
1 (4,) 4
5182
5182


In [104]:
#판다스 데이터 프레임
df =pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=['a','b','c'],columns=['A','B','C'])
df

A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [124]:
#테스트
import numpy as np
import pandas as pd

#두 개의 시리즈 데이터
print('인구수 시리즈 데이터:')
population_dict ={
    'korea':5182,
    'japan':12622,
    'china':141178,
    'usa':32976
}
population = pd.Series(population_dict)
print(population)

print('GDP 시리즈 데이터:')
GDP_dict ={
    'korea':169320000,
    'japan':516700000,
    'china':140925000,
    'usa': 2041280000
}
GDP = pd.Series(GDP_dict)
print(GDP)
print('='*25)
print('데이터 프레임 생성')
country = pd.DataFrame({'population':population,'gdp':GDP})
country.index.name = "Country"
country.columns.name ="Info"
print(country.index, country.columns)
print(country.values, country.shape, country.size, country.ndim)
country

인구수 시리즈 데이터:
korea      5182
japan     12622
china    141178
usa       32976
dtype: int64
GDP 시리즈 데이터:
korea     169320000
japan     516700000
china     140925000
usa      2041280000
dtype: int64
데이터 프레임 생성
Index(['korea', 'japan', 'china', 'usa'], dtype='object', name='Country') Index(['population', 'gdp'], dtype='object', name='Info')
[[      5182  169320000]
 [     12622  516700000]
 [    141178  140925000]
 [     32976 2041280000]] (4, 2) 8 2


Info     population         gdp
Country                        
korea          5182   169320000
japan         12622   516700000
china        141178   140925000
usa           32976  2041280000

In [125]:
# 데이터 프레임의 요소 접근 방법, loc, iloc
country.loc['korea'],country.loc['usa']   #키값 기반으로
country.iloc[2],country.iloc[1]           #인덱스값 기반으로

(Info
 population       141178
 gdp           140925000
 Name: china, dtype: int64,
 Info
 population        12622
 gdp           516700000
 Name: japan, dtype: int64)

In [126]:
country.loc['korea':'japan',:'population']  # <= x <=

Info     population
Country            
korea          5182
japan         12622

In [127]:
country.iloc[0:2,:1]

Info     population
Country            
korea          5182
japan         12622

In [128]:
print(country.loc['japan':'usa','gdp':])
print(country.iloc[1:4,1:])

Info            gdp
Country            
japan     516700000
china     140925000
usa      2041280000
Info            gdp
Country            
japan     516700000
china     140925000
usa      2041280000


In [129]:
print(country.loc['japan':'usa',:'population'])
print(country.iloc[1:4,:1])

Info     population
Country            
japan         12622
china        141178
usa           32976
Info     population
Country            
japan         12622
china        141178
usa           32976


In [140]:
# 컬럼추가
# country['test']=[11,22,33,44]
# country = country.drop('test',axis=1)
gdpper = country['gdp'] /country['population']
country['gdp_per'] = gdpper
country

Info     population           gdp       gdp_per
Country                                        
korea        5182.0  1.693200e+08  32674.642995
japan       12622.0  5.167000e+08  40936.460149
china      141178.0  1.409250e+08    998.207936
usa         32976.0  2.041280e+09  61901.989326
india       14222.0  1.505050e+08  10582.548165
africa     123456.0  7.777777e+06     63.000397

In [154]:
# 행추가
country.loc['india'] = [142222,150505000,152222]
country.loc['india','gdp_per']=country.loc['india','gdp']/country.loc['india','population']
country

Info     population           gdp       gdp_per
Country                                        
korea        5182.0  1.693200e+08  32674.642995
japan       12622.0  5.167000e+08  40936.460149
china      141178.0  1.409250e+08    998.207936
usa         32976.0  2.041280e+09  61901.989326
india      142222.0  1.505050e+08   1058.239935

In [223]:
# 행추가 방법2
africa = pd.Series(data =[123456,7777777],index=['population','gdp'])
print(africa)
country.loc['africa']=africa
country.loc['africa','gdp_per']=country.loc['africa','gdp']/country.loc['africa','population']
country

population     123456
gdp           7777777
dtype: int64


Info     population           gdp       gdp_per
Country                                        
korea        5182.0  1.693200e+08  32674.642995
japan       12622.0  5.167000e+08  40936.460149
china      141178.0  1.409250e+08    998.207936
usa         32976.0  2.041280e+09  61901.989326
india      142222.0  1.505050e+08   1058.239935
africa     123456.0  7.777777e+06     63.000397

In [156]:
#열제거drop(이름,axis=0)
country.drop('africa',axis=0,inplace =True) #inplace = True 담아주는행위 없이 바로 적용됨
country

Info     population           gdp       gdp_per
Country                                        
korea        5182.0  1.693200e+08  32674.642995
japan       12622.0  5.167000e+08  40936.460149
china      141178.0  1.409250e+08    998.207936
usa         32976.0  2.041280e+09  61901.989326
india      142222.0  1.505050e+08   1058.239935

In [157]:
# 결측값(NaN) 확인
# country.isnull().sum()

In [160]:
#테스트1
country[country['population'] > 140000]

Info     population          gdp      gdp_per
Country                                      
china      141178.0  140925000.0   998.207936
india      142222.0  150505000.0  1058.239935

In [171]:
#테스트2 조건, 슬라이싱(loc,iloc 필수)
country[(country['population'] > 10000) & (country['population'] < 100000)].loc[:,:'population']

Info     population
Country            
japan       12622.0
usa         32976.0

In [303]:
# 기본적인 방법
data = {
    '이름':['홍길동','박철수','김영희'],
    '국어':[80,60,70],
    '수학':[70,70,90],
    '영어':[80,80,80]
}
df = pd.DataFrame(data)

# 키값쌍으로 리스트에 저장하는 방법
data = [
    {'이름':'홍길동','국어':80,'수학':70,'영어':80},
    {'이름':'박철수','국어':60,'수학':70,'영어':80},
    {'이름':'김영희','국어':70,'수학':90,'영어':80},
]

# 리스트에 튜플로 저장하는 방법
data =[
     ('홍길동',80,70,80),
     ('박철수',60,70,80),
     ('김영희',70,90,80),
      ]
df= pd.DataFrame(data,columns=['이름','국어','수학','영어'])
df

이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [6]:
import numpy as np
import pandas as pd
# data0 =[
#      ('홍길동',80,70,80),
#      ('박철수',60,70,80),
#      ('김영희',70,90,80),
#       ]
# data=np.array(data0)
data = np.array([['홍길동',80,70,80],['박철수',60,70,80],['김영희',70,90,80]])
df = pd.DataFrame(data,columns=['이름','국어','수학','영어'])
df

이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [331]:
name = ['홍길동','박철수','김영희']
score1=[80,60,70]
score2=[70,70,90]
score3=[80,80,80]
score= pd.DataFrame({'이름':name,'국어':score1,'수학':score2,'영어':score3})
score

이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [2]:
# Q2
score.iloc[1:2,:3]
score.loc[1:1,:'수학']

이름  국어  수학
1  박철수  60  70

In [7]:
# Q3
# Q3 = score[score['국어']>= 70].loc[:,:]

#넘파이사용
df[df['국어'].astype(int)>=70]

이름  국어  수학  영어
0  홍길동  80  70  80
2  김영희  70  90  80

In [321]:
# Q4
score['평균'] = (score['국어']+score['수학']+score['영어'])/3
score.round()

이름  국어  수학  영어    평균
0  홍길동  80  70  80  77.0
1  박철수  60  70  80  70.0
2  김영희  70  90  80  80.0
3  최자바  55  95  70  73.0

In [322]:
# Q5
최자바 = pd.Series(['최자바',55,95,70],index=['이름','국어','수학','영어'])
score.loc[3]=최자바
score.loc[3,'평균']= (score.loc[3,'국어']+score.loc[3,'수학']+score.loc[3,'영어'])/3
score.round()

이름  국어  수학  영어    평균
0  홍길동  80  70  80  77.0
1  박철수  60  70  80  70.0
2  김영희  70  90  80  80.0
3  최자바  55  95  70  73.0